# Generated by Django 3.1.2 on 2021-01-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jogadores',
            fields=[
                ('id_jogador', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_nasc', models.DateTimeField(blank=True, null=True)),
                ('nivel', models.IntegerField(blank=True, default=0, null=True)),
                ('jogos_realizados', models.IntegerField(blank=True, default=0, null=True)),
                ('jogos_furados', models.IntegerField(blank=True, default=0, null=True)),
                ('sexo_jogador', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
                ('contato', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_jogador', models.CharField(choices=[('L', 'Linha'), ('G', 'Goleiro')], default='L', max_length=1)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'jogador',
                'verbose_name_plural': 'jogadores',
                'db_table': 'jogadores',
                'managed': True,
            },
        ),
    ]
