# Generated by Django 3.1.5 on 2021-01-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jogadores',
            fields=[
                ('id_quadra', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('tipo_quadra', models.CharField(choices=[('s', 'Salão'), ('c', 'Campo'), ('a', 'Areia'), ('soc', 'Society')], default='s', max_length=3)),
                ('contato', models.CharField(blank=True, max_length=50, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'quadra',
                'verbose_name_plural': 'quadras',
                'db_table': 'quadras',
                'managed': True,
            },
        ),
    ]
